spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DEV_USER:quiz}
    url: jdbc:postgresql://${DEV_HOST:localhost}:5432/${DEV_DB:quizdb}
    password: ${DEV_PASSWORD:quiz123}
  jpa:
    hibernate:
      ddl-auto: update