-- Baseline: schema já existente em produção antes da adoção do Flyway.
-- Reflete exatamente o que o Hibernate (ddl-auto=update) já vinha criando,
-- para que bancos existentes (com dados) possam ser "batizados" nesta
-- versão via spring.flyway.baseline-on-migrate, sem reexecutar nada.
-- Bancos novos (dev/CI) executam esta migration normalmente do zero.

CREATE TABLE tb_user (
    uuid     uuid NOT NULL,
    email    varchar(255),
    name     varchar(255),
    password varchar(255),
    role     varchar(255),
    CONSTRAINT tb_user_pkey PRIMARY KEY (uuid),
    CONSTRAINT tb_user_role_check CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE tb_theme (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    name         varchar(255),
    image_url    varchar(255),
    creator_uuid uuid,
    CONSTRAINT tb_theme_pkey PRIMARY KEY (id),
    CONSTRAINT fkai4stbvop91o7guij0llqd3s5 FOREIGN KEY (creator_uuid) REFERENCES tb_user (uuid)
);

CREATE INDEX idx_theme_creator_uuid ON tb_theme (creator_uuid);

CREATE TABLE tb_question (
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    title            varchar(255),
    image_url        varchar(255),
    image_base64one  text,
    image_base64two  text,
    images_order     varchar(255),
    creator_uuid     uuid,
    theme_id         bigint,
    CONSTRAINT tb_question_pkey PRIMARY KEY (id),
    CONSTRAINT fkdvyq8pwigr3wbvnoswql1de17 FOREIGN KEY (creator_uuid) REFERENCES tb_user (uuid),
    CONSTRAINT fkmoxds7kpemks900fehed7n2i3 FOREIGN KEY (theme_id) REFERENCES tb_theme (id)
);

CREATE INDEX idx_question_theme_id ON tb_question (theme_id);
CREATE INDEX idx_question_creator_uuid ON tb_question (creator_uuid);

CREATE TABLE tb_alternative (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    text        varchar(255),
    correct     boolean,
    question_id bigint,
    CONSTRAINT tb_alternative_pkey PRIMARY KEY (id),
    CONSTRAINT fk9301kmeov1aagf7em6nkwiyl3 FOREIGN KEY (question_id) REFERENCES tb_question (id)
);

CREATE TABLE tb_response (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    date_time      date,
    user_uuid      uuid,
    question_id    bigint,
    alternative_id bigint,
    game_mode      varchar(255),
    CONSTRAINT tb_response_pkey PRIMARY KEY (id),
    CONSTRAINT fkqf8drsm39xnek5ow8g1cjof7g FOREIGN KEY (user_uuid) REFERENCES tb_user (uuid),
    CONSTRAINT fkcfwpsgjtf3g78suqt4vsiph2o FOREIGN KEY (question_id) REFERENCES tb_question (id),
    CONSTRAINT fkjpnefqgx25ltwskdvhs3e2n4d FOREIGN KEY (alternative_id) REFERENCES tb_alternative (id),
    CONSTRAINT tb_response_game_mode_check CHECK (game_mode IN ('SINGLE_PLAYER', 'MULTIPLAYER'))
);

CREATE INDEX idx_response_user_uuid ON tb_response (user_uuid);
CREATE INDEX idx_response_question_id ON tb_response (question_id);
CREATE INDEX idx_response_game_mode_date_time ON tb_response (game_mode, date_time);

CREATE TABLE tb_score (
    id        bigint GENERATED BY DEFAULT AS IDENTITY,
    result    double precision,
    user_uuid uuid,
    theme_id  bigint,
    CONSTRAINT tb_score_pkey PRIMARY KEY (id),
    CONSTRAINT fk7pfv0i1khryqnlpiq4tfp81pd FOREIGN KEY (user_uuid) REFERENCES tb_user (uuid),
    CONSTRAINT fkhspupvfvm9y68pxagjovnbu4w FOREIGN KEY (theme_id) REFERENCES tb_theme (id)
);

CREATE TABLE tb_statistic (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    creator_id          uuid,
    student_name        varchar(255),
    theme_name          varchar(255),
    percentagem_of_hits double precision,
    date                date,
    CONSTRAINT tb_statistic_pkey PRIMARY KEY (id)
);

CREATE TABLE tb_room (
    room_id          uuid NOT NULL,
    creator_uuid     uuid,
    selected_quiz_id bigint,
    started          boolean NOT NULL,
    CONSTRAINT tb_room_pkey PRIMARY KEY (room_id),
    CONSTRAINT fkdob5y693lcd49la9lcgajnl18 FOREIGN KEY (creator_uuid) REFERENCES tb_user (uuid)
);

CREATE TABLE tb_room_players (
    room_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT fkpjwi4o2vuu7x1r11xgt0b6tyu FOREIGN KEY (room_id) REFERENCES tb_room (room_id),
    CONSTRAINT fk8434kbkckglytryx0kdwt126m FOREIGN KEY (user_id) REFERENCES tb_user (uuid)
);
