ALTER TABLE tb_user
    ADD COLUMN xp integer NOT NULL DEFAULT 0,
    ADD COLUMN level integer NOT NULL DEFAULT 1;

ALTER TABLE tb_score
    ADD COLUMN created_at timestamp NOT NULL DEFAULT now();

CREATE TABLE tb_friendship (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_uuid uuid NOT NULL REFERENCES tb_user (uuid),
    addressee_uuid uuid NOT NULL REFERENCES tb_user (uuid),
    status varchar(20) NOT NULL,
    created_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX idx_friendship_requester ON tb_friendship (requester_uuid);
CREATE INDEX idx_friendship_addressee ON tb_friendship (addressee_uuid);

CREATE TABLE tb_match_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid uuid NOT NULL REFERENCES tb_user (uuid),
    mode varchar(20) NOT NULL,
    theme_name varchar(255) NOT NULL,
    score integer NOT NULL,
    total integer NOT NULL,
    played_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX idx_match_history_user ON tb_match_history (user_uuid);
