ALTER TABLE tb_user
    ADD COLUMN coins integer NOT NULL DEFAULT 0;

CREATE TABLE tb_wallet_transaction (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid uuid NOT NULL REFERENCES tb_user (uuid),
    type varchar(20) NOT NULL,
    amount integer NOT NULL,
    reason varchar(255) NOT NULL,
    created_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX idx_wallet_transaction_user ON tb_wallet_transaction (user_uuid);

CREATE TABLE tb_user_inventory_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid uuid NOT NULL REFERENCES tb_user (uuid),
    item_code varchar(50) NOT NULL,
    purchased_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_inventory_item UNIQUE (user_uuid, item_code)
);

CREATE INDEX idx_user_inventory_item_user ON tb_user_inventory_item (user_uuid);
