-- Conteúdos do tema (texto livre) e materiais de apoio associados.

ALTER TABLE tb_theme ADD COLUMN description text;

CREATE TABLE tb_material (
    id       bigint GENERATED BY DEFAULT AS IDENTITY,
    name     varchar(255),
    link     varchar(1000),
    type     varchar(20),
    theme_id bigint,
    CONSTRAINT tb_material_pkey PRIMARY KEY (id),
    CONSTRAINT fk_material_theme FOREIGN KEY (theme_id) REFERENCES tb_theme (id)
);

CREATE INDEX idx_material_theme_id ON tb_material (theme_id);
